import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.scss";
import "leaflet/dist/leaflet.css";
import NavigationMenu from "@/components/navigation-menu";
import { AppContextProvider } from "@/contexts/app-context";
import Image from "next/image";
import ShattafeMarker from "../../public/shattafe-marker.png";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Where's My Shattafe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}`}>
        <AppContextProvider>
          <NavigationMenu />
          <div className="main">
            <header className="home-page__header">
              <div className="home-page__logo">
                <Image src={ShattafeMarker} alt="Shattafe Marker" fill placeholder="blur" />
              </div>
              <h1 className="home-page__title">Where&apos;s My Shattafe?</h1>
            </header>
            {children}
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
